pipeline.rmd:
  path: dev/pipeline.rmd
  state: active
  R:
  - R/download_data.R
  - R/data-wrangling.R
  tests:
  - tests/testthat/test-download_data.R
  - tests/testthat/test-data-wrangling.R
  vignettes: vignettes/minimal.Rmd
  inflate:
    flat_file: dev/pipeline.rmd
    vignette_name: Minimal
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
