pipeline.rmd:
  path: dev/pipeline.rmd
  state: active
  R: R/traffic_incidents_wrangling.R
  tests: tests/testthat/test-traffic_incidents_wrangling.R
  vignettes: vignettes/minimal.Rmd
  inflate:
    flat_file: dev/pipeline.rmd
    vignette_name: Minimal
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
