# WARNING - Generated by {fusen} from dev/pipeline.rmd: do not edit by hand

# Variables used in tests
traffic_incidents_url <- "https://data.calgary.ca/resource/35ra-9556.csv"
construction_detours_url <- "https://data.calgary.ca/resource/w8zq-79bq.csv"

# Running the functions
download_data(url = traffic_incidents_url, destfile = "../00_data/traffic_incidents.csv")
download_data(url = construction_detours_url, destfile = "../00_data/construction_detours.csv")

# Testing the functions worked properly
testthat::expect_true(file.exists("../00_data/traffic_incidents.csv"))
testthat::expect_true(file.exists("../00_data/construction_detours.csv"))

