# WARNING - Generated by {fusen} from dev/pipeline.rmd: do not edit by hand

# traffic_incidents_url <- "https://data.calgary.ca/resource/35ra-9556.csv"
# 
# # Download data
# download_data(url = traffic_incidents_url, destfile = "traffic_incidents.csv")
# 
# # Load data
# traffic_incidents_raw <- readr::read_csv("traffic_incidents.csv",show_col_types = FALSE)
# 
# # Run the function
# traffic_incidents <- traffic_incidents_wrangling(traffic_incidents_raw)
# 
# # Test that it worked
# testthat::expect_true("start_dt" %in% colnames(traffic_incidents))

# construction_detours_url <- "https://data.calgary.ca/resource/w8zq-79bq.csv"
# # Download data
# download_data(url = construction_detours_url, destfile = "construction_detours.csv")
# 
# # Load data
# construction_detours_raw <- readr::read_csv("construction_detours.csv")
# 
# # Run the function
# construction_detours <- construction_detours_wrangling(construction_detours_raw)
# 
# # Test that it worked
# testthat::expect_true("start_dt" %in% colnames(construction_detours))
