# WARNING - Generated by {fusen} from dev/pipeline.rmd: do not edit by hand

url <- "https://data.calgary.ca/resource/35ra-9556.csv"

# Download data
# download.file(url,testthat::test_path("testdata","traffic_incidents.csv"))
raw_data <- readr::read_csv(url,show_col_types = FALSE)

# Run the function
traffic_incidents <- traffic_incidents_wrangling(raw_data)

 # Tests
testthat::test_that("Check if cleaning names worked", {
  expect_true("start_dt" %in% colnames(traffic_incidents))
})


url <- "https://data.calgary.ca/resource/w8zq-79bq.csv"

# Download data
#download.file(url,testthat::test_path("testdata","construction_detours.csv"))
raw_data <- readr::read_csv(url,show_col_types = FALSE)

# Run the function
construction_detours <- construction_detours_wrangling(raw_data)

 # Tests
testthat::test_that("Check if cleaning names worked", {
  expect_true("start_dt" %in% colnames(construction_detours))
})

