# WARNING - Generated by {fusen} from dev/pipeline.rmd: do not edit by hand

# Download data
download_data(url = traffic_incidents_url, destfile = "../00_data/traffic_incidents.csv")

# Load data
traffic_incidents_raw <- readr::read_csv("../00_data/traffic_incidents.csv")

# Run the function
traffic_incidents <- traffic_incidents_wrangling(traffic_incidents_raw)

# Test that it worked
testthat::expect_true("start_dt" %in% colnames(traffic_incidents))

# Download data
download_data(url = construction_detours_url, destfile = "../00_data/construction_detours.csv")

# Load data
construction_detours_raw <- readr::read_csv("../00_data/construction_detours.csv")

# Run the function
construction_detours <- construction_detours_wrangling(construction_detours_raw)

# Test that it worked
testthat::expect_true("start_dt" %in% colnames(construction_detours))
