# WARNING - Generated by {fusen} from dev/pipeline.rmd: do not edit by hand

#' download_data gets raw data from the YYC Open Data Portal, or really any provided url
#'
#' @param url Persistent url to the data
#' @param destfile Destination to save downloaded file, including the file name
#' @importFrom utils download.file
#' @return csv file
#' @export
#' @examples
#' traffic_incidents_url <- "https://data.calgary.ca/resource/35ra-9556.csv"
#'
#' # Running the functions
#' download_data(url = traffic_incidents_url, destfile = "00_data/traffic_incidents.csv")
#'

download_data <- function(url, destfile) {
    download.file(
        url = url, 
        destfile = destfile,
        overwrite = TRUE
        )
  }
