# WARNING - Generated by {fusen} from dev/pipeline.rmd: do not edit by hand

#' traffic_incidents_wrangling cleans the traffic incidents raw data
#'
#' @param traffic_incidents_raw_data Traffic incidents raw data
#' @details This function cleans the column names and converts the date columns to date time format
#' @importFrom dplyr mutate
#' @importFrom janitor clean_names
#' @return data frame
#' @export

traffic_incidents_wrangling <- function(traffic_incidents_raw_data) {
    traffic_incidents_raw |>
    janitor::clean_names() |>
    mutate(
    start_dt = lubridate::ymd_hms(start_dt,tz = "Canada/Mountain"),
    modified_dt = lubridate::ymd_hms(modified_dt,tz = "Canada/Mountain"),
        )
}

#' construction_detours_wrangling cleans the traffic incidents raw data
#'
#' @param construction_detours_wrangling Construction detours raw data
#' @details This function cleans the column names and converts the date columns to date time format
#' @importFrom dplyr mutate
#' @importFrom janitor clean_names
#' @importFrom lubridate ymd_hms
#' @return data frame
#' @export
#' 
construction_detours_wrangling <- function(construction_detours_raw_data) {
    construction_detours_raw |>
    janitor::clean_names() |>
    mutate(
    start_dt = lubridate::ymd_hms(start_dt,tz = "Canada/Mountain"),
    end_dt = lubridate::ymd_hms(end_dt,tz = "Canada/Mountain")
        )
}
